👌 PERFORMANCE: big refactor to start getting start:dev auto-loader working
cezaraugusto/extension-create pull request #23
Opened 2023-04-23 03:35 UTC by itsbrex

2023-04-29 03:15 UTC, cezaraugusto requested changes
hi @itsbrex! Thanks for the contribution! extension-create is my favorite project, glad you found it useful.

Left a few comments, mostly to keep Chrome as default and remove the popup template which isn't supported.

2023-04-29 03:15 UTC, cezaraugusto commented on develop/start/config/browserSwitch.js
> +  return browserVendor
can you return Chrome here? at this point I can't support all browsers

```suggestion
  // TODO: Should default to user browser, not Chrome
  return new RunChromeExtension({extensionPath: projectDir})
```

2024-02-23 21:08 UTC, cezaraugusto commented
hi @itsbrex thanks for contributing!

I made significant changes in the project these days, so I'll have to close this one. The good news is that the project is working for Edge again. You can try `npx extension-create dev <path-to-your-extension>` and things should work as expected.

Would be great to have more contributions from you in the future. The project has many moving parts and expert help is always appreciated. Thanks!

2024-02-23 21:08 UTC, closed without merging

2024-03-15 08:24 UTC, itsbrex commented
@cezaraugusto so sorry for ghosting you here! Missed this notification. I need to turn off renovate bot notifications so I stop missing *actual* notifications. 🤦‍♂️